
MINIMAL_INIT=tests/minimal_init.lua

test: $(MINIMAL_INIT)
	NVIM_MINIMAL_INIT=$(MINIMAL_INIT) \
	nvim --headless -c "lua require('plenary.busted').run('tests/init_spec.lua')" +qa

$(MINIMAL_INIT):
	@echo "Creating $(MINIMAL_INIT)..."
	@mkdir -p tests
	@echo "-- minimal_init.lua autogenerated by Makefile" > $(MINIMAL_INIT)
	@echo "vim.opt.runtimepath:prepend(vim.fn.getcwd())" >> $(MINIMAL_INIT)
	@echo "vim.opt.runtimepath:prepend(vim.fn.stdpath('data') .. '/lazy/plenary.nvim')" >> $(MINIMAL_INIT)

clean:
	rm -f $(MINIMAL_INIT)

